### ISSUE TITLE
Temporary Solution?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/team-calendar#14]
Through discussion with FAC6 we concluded that the Google Calendar UI goes _most_ of the way to solving the issue of viewing other people's calendars.

So... for now we are not going to re-build the calendar UI.

Instead we are going to create a Guide for how to use Google Calendar and _require_ that everyone working with dwyl shares their google calendar. 
**_OR**_ we have a Team Calendar which anyone can create events on.

Please discuss.

**Comment by sohilpandya** [comment]
Strongly disagree, some of us took a liking to this project and really wanted to solve this problem.

**Comment by Joshua-Ronan-Phillips** [comment]
I think a team calendar would work best as some people might not want to share their personal appointments with the whole group. Another way around this would be for everyone to have a 'work' google calendar but I think a group calendar works better.

**Comment by iteles** [comment]
Personally, my google calendar environment is already a mess of 6 different calendars I manage for different parts of my life and other people's lives. 

I can't handle having 20 calendars in that single calendar environment, those little boxes just don't show me everything I need.

**Comment by nelsonic** [comment]
@iteles I *tried* to convey the *pain* :fire: of managing a schedule for a team or small company using GCal but the words failed me ... :cry: 
Several people did not *empathise* with the problem and as a result were *visibly disinterested* in solving it ...

**Microsoft** makers of *Outlook* recently paid [**$100M**](http://techcrunch.com/2015/02/04/microsoft-sunrise/) for [***Sunrise***](https://calendar.sunrise.am/) which is ***Beautiful UI*** on top of *existing* calendar systems: 
![sunrise ui](http://cdn1.knowyourmobile.com/sites/knowyourmobilecom/files/styles/gallery_wide/public/Array/sunrise.jpg?itok=PUWnGknP)

this *suggests* that there are *enough* people who *feel* the Calendar UI problem for MSFT to open their chequebook ...

Scheduling/Calendar UI is *far* from "*solved*". 
I *personally* don't *like* the GCal UI as it feels *cluttered* with only a handful of shared calendars:
<img width="1367" alt="google-calendar" src="https://cloud.githubusercontent.com/assets/194400/11407576/8e68f740-93ab-11e5-8237-51e254c4cb7d.png">

The point of this week/exercise was to get people to learn a tool they have never used to solve a problem they have not attempted before. I *thought* learning hapi *while* attempting to solve the **Calendar UI** problem would be quite challenging.

*However* I agree with @Conorc1000 that learning Hapi *while* trying to solve this problem might be a stretch for some people ... 

Lets re-visit the Team Calendar problem with people who *empathise* with it. :+1: 
Or we can all just use *Outlook*...?

**Comment by iteles** [comment]
:laughing: No. I agree with re-visiting this issue with people who are _interested_ in working on the problem. 

I need this badly, I just can't deal with the insanity of my GCal + spreadsheets + scattered notes on where everything is at anymore!

**Comment by tormod17** [comment]
Sounds good :+1:  , I think the issue today was most of us weren't understanding that google calendar had the functionality to share calendars and saw that is being the main problem so didn't see exactly what the problem we were trying to solve was (even though @nelsonic  did very clearly point this out and has do so again above). However,  during the open talk I thought there were some great ideas and gave  a clearer understanding of how to go about things. e.g. making the calendar specific to FAC, incorporating Meet-ups and events,  being able to assign attendees or meet-up duties, having a better UI/UX...... .I'd be hapi to give it another go (bit unsure if we need google calendar why not create our own)

**Comment by katpas** [comment]
I had a think about what a calendar MVP might look like. For finding who is free for projects we don't care about the day to day/hour by hour detail. We just need to know who is blocked out which weeks. That would remove some of the busyness and you could group people in teams too which could be collapsed. 

![img_20151127_132121](https://cloud.githubusercontent.com/assets/9627463/11442263/c6f1c360-950b-11e5-8828-6ed2895fd562.jpg)

**Comment by nelsonic** [comment]
@katpas :+1:

**Comment by msmichellegar** [comment]
Just want to say I'm devastated that Sunrise was bought by Microsoft, and I'm currently in search of something ANYTHING that can possibly compare. RIP.

I liked the beautiful UI of Sunrise (and of its predecessor Tempo). There were also some cool extra features I loved: a daily pre-brief for your next day, integration with Google Calanders/Facebook/GitHub/Meetup/Tripit/literally everything.

**Comment by nelsonic** [comment]
Closing as very out-of-date. ✅ 
Hope everyone in this thread is well. ☀️ ❤️
