### ISSUE TITLE
seems a dead project? 

### ISSUE THREAD

**Issue by yrong** [dwyl/team-calendar#17]
You succeeded in cheating me. Nothing to do with the title or propaganda as `team-calendar`.  suggest to change the project name to something like `hapi-google-oauth-demo`

**Comment by nelsonic** [comment]
@yrong this project is "on hold" until we finish our other work.
It will be switched to `Elixir` in due course and will _use_ Google OAuth to retrieve calendar details.
Thanks for your interest. ☀️
